; GEL Sheaf Functor Seed (IUTT/Lisp formalism)
(defparameter *gel-sheaf-functor-seed*
  '(gel-sheaf-functor
     :id "GSF-0001"
     :formalism (IUTT Lisp)
     :functor "F_symbolic_index_to_gel_roots"
     :atlas-hash "97831fe2695e32d38d7091184314fd941e26516e6b324b0975f7c3caca5acedf"
     :symbolic-index-hash "2ec0a79669caed3c45fafd95008452e493b755a23197c2826824d40bafab8342"
     :sections (GSE-PREFIXES GSE-ROOTS GSE-SUFFIXES)
     :morphisms ((prefixes roots acts-on) (roots suffixes extends-with) (roots gel indexes-into))
     :populate-state pending-higher-order
     :seed-version v1))

(defparameter *gel-sheaf-section-seeds*
  '(
    (gel-sheaf-section :id "GSE-PREFIXES" :domain prefixes :root-entry-ids (IER-PFX-A IER-PFX-B IER-PFX-C IER-PFX-D IER-PFX-E IER-PFX-I IER-PFX-M IER-PFX-P IER-PFX-R IER-PFX-S IER-PFX-T IER-PFX-U) :populate-state pending-higher-order :seed-version v1)
    (gel-sheaf-section :id "GSE-ROOTS" :domain roots :root-entry-ids (IER-ROOT-A IER-ROOT-B IER-ROOT-C IER-ROOT-D IER-ROOT-E IER-ROOT-F IER-ROOT-G IER-ROOT-H IER-ROOT-I IER-ROOT-J IER-ROOT-K IER-ROOT-L IER-ROOT-M IER-ROOT-N IER-ROOT-O IER-ROOT-P IER-ROOT-Q IER-ROOT-R IER-ROOT-S IER-ROOT-T IER-ROOT-U IER-ROOT-V IER-ROOT-W IER-ROOT-X IER-ROOT-Y IER-ROOT-Z) :populate-state pending-higher-order :seed-version v1)
    (gel-sheaf-section :id "GSE-SUFFIXES" :domain suffixes :root-entry-ids (IER-SFX-A IER-SFX-B IER-SFX-C IER-SFX-D IER-SFX-E IER-SFX-F IER-SFX-G IER-SFX-H IER-SFX-I IER-SFX-J IER-SFX-K IER-SFX-L IER-SFX-M IER-SFX-N IER-SFX-O IER-SFX-P IER-SFX-R IER-SFX-S IER-SFX-T IER-SFX-U IER-SFX-V IER-SFX-W IER-SFX-X IER-SFX-Y IER-SFX-Z) :populate-state pending-higher-order :seed-version v1)
  ))

(defparameter *gel-encyclopediac-root-seeds*
  '(
    (gel-root :id "IER-PFX-A" :domain prefixes :index-letter a :entry-count 2 :symbolic-role prefix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-PFX-B" :domain prefixes :index-letter b :entry-count 1 :symbolic-role prefix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-PFX-C" :domain prefixes :index-letter c :entry-count 1 :symbolic-role prefix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-PFX-D" :domain prefixes :index-letter d :entry-count 1 :symbolic-role prefix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-PFX-E" :domain prefixes :index-letter e :entry-count 1 :symbolic-role prefix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-PFX-I" :domain prefixes :index-letter i :entry-count 2 :symbolic-role prefix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-PFX-M" :domain prefixes :index-letter m :entry-count 2 :symbolic-role prefix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-PFX-P" :domain prefixes :index-letter p :entry-count 2 :symbolic-role prefix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-PFX-R" :domain prefixes :index-letter r :entry-count 1 :symbolic-role prefix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-PFX-S" :domain prefixes :index-letter s :entry-count 2 :symbolic-role prefix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-PFX-T" :domain prefixes :index-letter t :entry-count 1 :symbolic-role prefix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-PFX-U" :domain prefixes :index-letter u :entry-count 1 :symbolic-role prefix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-A" :domain roots :index-letter a :entry-count 1725 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-B" :domain roots :index-letter b :entry-count 1507 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-C" :domain roots :index-letter c :entry-count 2716 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-D" :domain roots :index-letter d :entry-count 1487 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-E" :domain roots :index-letter e :entry-count 1079 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-F" :domain roots :index-letter f :entry-count 996 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-G" :domain roots :index-letter g :entry-count 984 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-H" :domain roots :index-letter h :entry-count 1014 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-I" :domain roots :index-letter i :entry-count 778 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-J" :domain roots :index-letter j :entry-count 231 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-K" :domain roots :index-letter k :entry-count 302 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-L" :domain roots :index-letter l :entry-count 818 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-M" :domain roots :index-letter m :entry-count 1659 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-N" :domain roots :index-letter n :entry-count 548 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-O" :domain roots :index-letter o :entry-count 642 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-P" :domain roots :index-letter p :entry-count 2180 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-Q" :domain roots :index-letter q :entry-count 159 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-R" :domain roots :index-letter r :entry-count 993 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-S" :domain roots :index-letter s :entry-count 2498 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-T" :domain roots :index-letter t :entry-count 1361 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-U" :domain roots :index-letter u :entry-count 258 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-V" :domain roots :index-letter v :entry-count 434 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-W" :domain roots :index-letter w :entry-count 452 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-X" :domain roots :index-letter x :entry-count 17 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-Y" :domain roots :index-letter y :entry-count 83 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-ROOT-Z" :domain roots :index-letter z :entry-count 79 :symbolic-role lexeme-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-A" :domain suffixes :index-letter a :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-B" :domain suffixes :index-letter b :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-C" :domain suffixes :index-letter c :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-D" :domain suffixes :index-letter d :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-E" :domain suffixes :index-letter e :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-F" :domain suffixes :index-letter f :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-G" :domain suffixes :index-letter g :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-H" :domain suffixes :index-letter h :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-I" :domain suffixes :index-letter i :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-J" :domain suffixes :index-letter j :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-K" :domain suffixes :index-letter k :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-L" :domain suffixes :index-letter l :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-M" :domain suffixes :index-letter m :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-N" :domain suffixes :index-letter n :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-O" :domain suffixes :index-letter o :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-P" :domain suffixes :index-letter p :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-R" :domain suffixes :index-letter r :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-S" :domain suffixes :index-letter s :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-T" :domain suffixes :index-letter t :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-U" :domain suffixes :index-letter u :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-V" :domain suffixes :index-letter v :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-W" :domain suffixes :index-letter w :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-X" :domain suffixes :index-letter x :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-Y" :domain suffixes :index-letter y :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
    (gel-root :id "IER-SFX-Z" :domain suffixes :index-letter z :entry-count 1 :symbolic-role suffix-local-universe :populate-state pending-higher-order :seed-version v1)
  ))
